name: mockito_freezed

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  flutter_test:
    sdk: flutter
#  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
